function [ handles ] = create_ac_panel_MartCalc( handles, parent_panel, criterion_name, default_value, criterion_number)
% CREATE_ASC_PANEL_MARTCALC

    % position of criterion in asc list
% % %     postion_in_asc_list = handles.asc_status(criterion_number);

    %%% create panel and text fields
    % parent panel for actual selection criterion
    if (parent_panel == handles.pan_asc) % panel for active selection criteria for calculation of laths
        tag = ['pan_asc_entry',num2str(criterion_number)]; %tag with number of position in list
        ac_number = handles.asc_number; % number of active criteria
        maxcrit_number = handles.asc_maxcrit; % maximum number of criteria
        
    elseif (parent_panel == handles.pan_amc) % panel for mixing of lath solutions to blocks
        tag = ['pan_amc_entry',num2str(criterion_number)]; %tag with number of position in list
        ac_number = handles.amc_number; % number of active criteria
        maxcrit_number = handles.amc_maxcrit; % maximum number of criteria
    else
        error('This parent is not considered for generation of new panels.')
    end
        
    
    handles.pan_ac_entry = uipanel('Parent',parent_panel,...
    'FontSize',12,...
    'Position', [0.01 (((parent_panel.Position(4)-ac_number*(parent_panel.Position(4)/maxcrit_number))/parent_panel.Position(4))+0.01) 0.985 ((parent_panel.Position(4)/maxcrit_number)/parent_panel.Position(4)-0.01)],...
    'Tag', tag );
            
% % %             guidata(hObject, handles); % Update handles structure
            
     % text field for displaying the postion of the criterion in the
     % list
     tag2 = [tag,'_edtx_num'];
     handles.pan_ac_entry_edtxt_num = uicontrol('Parent',handles.pan_ac_entry,...
     'Style','edit',...
     'FontSize',12,...
     'units','normalize', ...
     'BackgroundColor', [0.831, 0.816, 0.784],...
     'String',num2str(ac_number),...
     'Position', [0.005, 0.05, 0.035, 0.9],...
     'Enable', 'inactive',...
     'Value', criterion_number,...
     'Tag',tag2,...
     'Visible', 'on');
            
     % text field for displaying the description of the criterion
     tag3 = [tag,'_edtx_name'];
     handles.pan_ac_entry_edtxt_name = uicontrol('Parent',handles.pan_ac_entry,...
     'Style','edit',...
     'FontSize',12,...
     'units','normalize', ...
     'BackgroundColor', [0.831, 0.816, 0.784],...
     'String',criterion_name,...
     'Position', [0.05, 0.05, 0.71, 0.9],...
     'Enable', 'inactive',...
     'Value', criterion_number,...
     'Tag',tag3,...
     'Visible', 'on');
            
     % active text field for entering an value for the criterion
     tag4 = [tag,'_edtx_val'];
     handles.pan_ac_entry_edtxt_val = uicontrol('Parent',handles.pan_ac_entry,...
     'Style','edit',...
     'FontSize',12,...
     'units','normalize', ...
     'BackgroundColor', [0.94, 0.94, 0.94],...
     'String',num2str(default_value),...
     'Position', [0.77, 0.05, 0.135, 0.9],...
     'Enable', 'on',...
     'Value', criterion_number,...
     'Tag',tag4,...
     'Visible', 'on');
            
     % pushbutton for deletion of asc panel
     tag5 = [tag,'_del'];
     handles.pan_ac_entry_del = uicontrol('Parent',handles.pan_ac_entry,...
     'Style','pushbutton',...
     'FontSize',12,...
     'units','normalize', ...
     'BackgroundColor', [0.94, 0.94, 0.94],...
     'String','Delete',...
     'Position', [0.91, 0.05, 0.08, 0.9],...
     'Enable', 'on',...
     'Value', criterion_number,...
     'Visible', 'on',...
     'Tag',tag5,...
     'Callback',@delete_ac_MartCalc);

end

