function [ handles ] = create_asc_panel_MartCalc( handles, parent_panel, criterion_name, default_value, criterion_number)
% CREATE_ASC_PANEL_MARTCALC

    % position of criterion in asc list
    % postion_in_asc_list = handles.asc_status(criterion_number);    
    
    switch parent_panel
        case handles.pan_asc_IPS
            tag = ['pan_asc_entry_IPS',num2str(criterion_number)]; %tag with number of position in list
            asc_number = handles.asc_number_IPS;
            maxcrit_number = handles.asc_IPS_maxcrit;
        case handles.pan_asc_ILS
            tag = ['pan_asc_entry_ILS',num2str(criterion_number)]; %tag with number of position in list
            asc_number = handles.asc_number_ILS;
            maxcrit_number = handles.asc_ILS_maxcrit;
        case handles.pan_asc_blocks
            tag = ['pan_asc_entry_blocks',num2str(criterion_number)]; %tag with number of position in list
            asc_number = handles.asc_number_blocks;
            maxcrit_number = handles.asc_blocks_maxcrit;     
        otherwise
            error('This parent is not considered for deletion of panels')
    end
    
    %% create panel panel for actual selection criterion    
    handles.pan_asc_entry = uipanel('Parent', parent_panel,... %handles.pan_asc,...
    'FontSize',10,...
    'Position', [0.01 (((parent_panel.Position(4) - asc_number*(parent_panel.Position(4)/maxcrit_number)) / parent_panel.Position(4) )-0.02 ) 0.985 1./maxcrit_number],...
    'Tag', tag );
            
    %% create text fields          
     % text field for displaying the postion of the criterion in the list
     tag2 = [tag,'_edtx_num'];
     handles.pan_asc_entry_edtxt_num = uicontrol('Parent',handles.pan_asc_entry,...
     'Style','edit',...
     'FontSize',10,...
     'units','normalize', ...
     'FontUnits','normalized',...
     'BackgroundColor', [0.831, 0.816, 0.784],...
     'String',num2str(asc_number),...
     'Position', [0.005, 0.05, 0.035, 0.9],...
     'Enable', 'inactive',...
     'Value', criterion_number,...
     'Tag',tag2,...
     'Visible', 'on');
            
     % text field for displaying the description of the criterion
     tag3 = [tag,'_edtx_name'];
     handles.pan_asc_entry_edtxt_name = uicontrol('Parent',handles.pan_asc_entry,...
     'Style','edit',...
     'FontSize',10,...
     'units','normalize', ...
     'FontUnits','normalized',...
     'BackgroundColor', [0.831, 0.816, 0.784],...
     'String',criterion_name,...
     'Position', [0.05, 0.05, 0.71, 0.9],...
     'Enable', 'inactive',...
     'Value', criterion_number,...
     'Tag',tag3,...
     'Visible', 'on');
            
     % active text field for entering an value for the criterion
     tag4 = [tag,'_edtx_val'];
     handles.pan_asc_entry_edtxt_val = uicontrol('Parent',handles.pan_asc_entry,...
     'Style','edit',...
     'FontSize',10,...
     'units','normalize', ...
     'FontUnits','normalized',...
     'BackgroundColor', [0.94, 0.94, 0.94],...
     'String',num2str(default_value),...
     'Position', [0.77, 0.05, 0.135, 0.9],...
     'Enable', 'on',...
     'Value', criterion_number,...
     'Tag',tag4,...
     'Visible', 'on');
            
     % pushbutton for deletion of asc panel
     tag5 = [tag,'_del'];
     handles.pan_asc_entry_del = uicontrol('Parent',handles.pan_asc_entry,...
     'Style','pushbutton',...
     'FontSize',10,...
     'units','normalize', ...
     'FontUnits','normalized',...
     'BackgroundColor', [0.94, 0.94, 0.94],...
     'String','Delete',...
     'Position', [0.91, 0.05, 0.08, 0.9],...
     'Enable', 'on',...
     'Value', criterion_number,...
     'Visible', 'on',...
     'Tag',tag5,...
     'Callback',@delete_asc_MartCalc); 
     % PET: @(x)parameterfun(x,a,b,c) --- @delete_asc_MartCalc); --> not
     % working - introduced a handle variable to choose which is deleted!

end

